name: Testing

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt install -y python3-tk
        sudo apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pytest
      run: |
        xvfb-run --auto-servernum pytest
